namespace DataRefresh.TimeLimited
{
    /// <summary>
    /// The different modes of activation a date range can be in
    /// </summary>
    public enum DateRangeActivation
    {
        /// <summary>
        /// This date range is empty -- this typically means that this date
        /// range was generated by importing a database record with no date
        /// range information.
        /// </summary>
        Empty = 0,
        /// <summary>
        /// This date range causes the parent content to become inactive
        /// </summary>
        Inactive,
        /// <summary>
        /// This date range causes the parent content to become active
        /// </summary>
        Active
    }
}
